### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by FillHK** [d3vilh/raspberry-gateway#2]
` ansible-playbook main.yml
[WARNING]: Could not match supplied host pattern, ignoring: raspberry-gateway

PLAY [raspberry-gateway] *****************************************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP ********************************************************************************************************************************************************`

**Comment by d3vilh** [comment]
Hi @FillHK 
Do you trying to install it on remote host or local?
Could you double check inventory.ini file?
You have to comment out one of the lines there.

**Comment by FillHK** [comment]
I am trying to install it on local
Raspberry is connected to the router over LAN and has IP 192.168.0.155
I am connected to the raspberry over SSH from another laptop from the same network
```
[internet_pi]
192.168.0.155 ansible_user=pi

# Comment out the previous line and uncomment this to run inside Rasberry Pi.
$127.0.0.1 ansible_connection=local ansible_user=pi
```

**Comment by d3vilh** [comment]
OK, then you are installing it locally on PI, in this case IP address configuration is not necessary.
Try this:
```[raspberry-gateway]
#192.168.0.155 ansible_user=pi
# Comment out the previous line and uncomment this to run inside Rasberry Pi.
127.0.0.1 ansible_connection=local ansible_user=pi

**Comment by FillHK** [comment]
Yes, already tried but:
`pi@raspberrypi:~/raspberry-gateway $ ansible-playbook main.yml
[WARNING]: Could not match supplied host pattern, ignoring: raspberry-gateway

PLAY [raspberry-gateway] *****************************************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP *******************************************************************************************************************************************************************************

pi@raspberrypi:~/raspberry-gateway $
`

**Comment by d3vilh** [comment]
Are you sure, there is no $ in front of 127.0.0.1 ?

**Comment by FillHK** [comment]
```
[internet_pi]
#192.168.0.155 ansible_user=pi

# Comment out the previous line and uncomment this to run inside Rasberry Pi.
127.0.0.1 ansible_connection=local ansible_user=pi

```

**Comment by d3vilh** [comment]
> [internet_pi]

Change it to` [raspberry-gateway]`
it should works fine then.

**Comment by FillHK** [comment]
Super, now it's in progress!

Thank you for so fast answers and provided resolutions, I hope the overall solution will cover my needs:
* pi-hole (for ads blocking)
* VPN for all clients connected to router

**Comment by d3vilh** [comment]
Thank you for the issue.
Yes it’s cover this needs, it’s main use case for me as well.

**Comment by FillHK** [comment]
Got one fatal:
```
TASK [Ensure OpenVPN is running.] ********************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))"}

RUNNING HANDLER [Restart openvpn] ********************************************************************************************************************************************************

PLAY RECAP *******************************************************************************************************************************************************************************
127.0.0.1                  : ok=13   changed=9    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0

```

**Comment by d3vilh** [comment]
> fetching server API version:

It happens when user ENVs was not refreshed after ansible and dependencies installation.

Try logout from pi, then login and run playbook again.

**Comment by FillHK** [comment]
Have it done.

One, I hope last question. Will it work with Hidemyass? (unable to find settings for this)

**Comment by d3vilh** [comment]
> Will it work with Hidemyass?
it is basically local VPN server with pi-hole and other things onboard.
So, you can install it on your home/office, route all traffic throe pi-hole/unbound and use as a single connection point for all the remote devices. It will block add. and screw DPI of your telecom service provider, so they will see only VPN tunnel towards single IP, but will not able to gather big data from you - DNS, IP, HTTP and other history.
I have couple of such servers located in different countries, so can use different locations, but all the IPs usually static.

Personally I don't believe to all these free/not free VPN providers, they have main income from selling your data while hiding behind fancy "secure" names.
