### ISSUE TITLE
Install failure - help please

### ISSUE THREAD

**Issue by SAINTVIII** [d3vilh/raspberry-gateway#33]
Hi folks - get this error when installing from the web interface. Any help appreciated please!

TASK [Install Docker Compose using Pip.] ***************************************
fatal: [raspberry_gateway]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip3", "install", "docker-compose"], "msg": "stdout: Collecting docker-compose\n  Using cached docker_compose-1.29.2-py2.py3-none-any.whl (114 kB)\nCollecting PyYAML<6,>=3.10\n  Using cached PyYAML-5.4.1.tar.gz (175 kB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n\n:stderr:   error: subprocess-exited-with-error\n  \n  × Getting requirements to build wheel did not run successfully.\n  │ exit code: 1\n  ╰─> [68 lines of output]\n      /tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`\n      !!\n      \n              ********************************************************************************\n              The license_file parameter is deprecated, use license_files instead.\n      \n              This deprecation is overdue, please update your project and remove deprecated\n              calls to avoid build errors in the future.\n      \n              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.\n              ********************************************************************************\n      \n      !!\n        parsed = self.parsers.get(option_name, lambda x: x)(value)\n      running egg_info\n      writing lib3/PyYAML.egg-info/PKG-INFO\n      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt\n      writing top-level names to lib3/PyYAML.egg-info/top_level.txt\n      Traceback (most recent call last):\n        File \"/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 353, in <module>\n          main()\n        File \"/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 335, in main\n          json_out['return_val'] = hook(**hook_input['kwargs'])\n                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        File \"/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 118, in get_requires_for_build_wheel\n          return hook(config_settings)\n                 ^^^^^^^^^^^^^^^^^^^^^\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py\", line 355, in get_requires_for_build_wheel\n          return self._get_build_requires(config_settings, requirements=['wheel'])\n
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py\", line 325, in _get_build_requires\n          self.run_setup()\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py\", line 341, in run_setup\n          exec(code, locals())\n        File \"<string>\", line 271, in <module>\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/__init__.py\", line 103, in setup\n          return distutils.core.setup(**attrs)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py\", line 185, in setup\n
return run_commands(dist)\n                 ^^^^^^^^^^^^^^^^^^\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py\", line 201, in run_commands\n          dist.run_commands()\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py\", line 969, in run_commands\n          self.run_command(cmd)\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py\", line 989, in run_command\n          super().run_command(command)\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py\", line 988, in run_command\n          cmd_obj.run()\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py\", line 318, in run\n          self.find_sources()\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py\", line 326, in find_sources\n          mm.run()\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py\", line 548, in run\n          self.add_defaults()\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py\", line 586, in add_defaults\n          sdist.add_defaults(self)\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/command/sdist.py\", line 113, in add_defaults\n          super().add_defaults()\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/sdist.py\", line 251, in add_defaults\n          self._add_defaults_ext()\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/sdist.py\", line 336, in _add_defaults_ext\n          self.filelist.extend(build_ext.get_source_files())\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        File \"<string>\", line 201, in get_source_files\n        File \"/tmp/pip-build-env-8uxvup47/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py\", line 107, in __getattr__\n          raise AttributeError(attr)\n      AttributeError: cython_sources\n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\nerror: subprocess-exited-with-error\n\n× Getting requirements to build wheel did not run successfully.\n│ exit code: 1\n╰─> See above for output.\n\nnote: This error originates from a subprocess, and is likely not a problem with pip.\n"}

PLAY RECAP *********************************************************************
raspberry_gateway          : ok=6    changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0

2023/11/03 10:09:54 exit status 2

**Comment by permanutry** [comment]
I had the same problem with the latest Raspbian. It does not matter if you are using webinstall or running with the cli.

The issue related to restricted pip usage and fix is to update docker installation task with the usage of apt instead of pip3.
Something like `sudo apt-get install -y docker-compose`

@d3vilh please take care, I know you have a solution already ;)

**Comment by d3vilh** [comment]
Somehow, I missed this issue. 
@SAINTVIII I just push the fix in the main branch.

**Comment by d3vilh** [comment]
Closing it as resolved.
