### ISSUE TITLE
./webinstall "segmentation fault"

### ISSUE THREAD

**Issue by Davide3i** [d3vilh/raspberry-gateway#38]
Hi.
I'm trying to run 
`./webinstall`
but unfortunately I'm getting _segmentation fault_.
If I run
`strace ./webinstall`
I get

> execve("./webinstall", ["./webinstall"], 0x7fffe50156f0 /* 48 vars */) = -1 EINVAL (Invalid argument)
+++ killed by SIGSEGV +++
Segmentation fault

Thanks!

**Comment by d3vilh** [comment]
Hi @Davide3i,
Could you share `uname -a` output?
I think you are running it on ARM7x or ARM6x.

If it is the case you need to download the correct binary, following by steps below.

```bash
nachalnik@tut:~/$ uname -a
Linux d3zero2-32 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
```
You could see `armv71` as current system architecture.

Download webinstall binary specific for your arch to the raspberry-gateway main directory:
* armv7x `wget https://github.com/d3vilh/raspberry-gtw-webconfig/raw/main/webinstall-arm7x`
* armv6x `wget https://github.com/d3vilh/raspberry-gtw-webconfig/raw/main/webinstall-arm6x`

```bash
nachalnik@tut:~/$ cd raspberry-gateway
nachalnik@tut:~/raspberry-gateway $ wget https://github.com/d3vilh/raspberry-gtw-webconfig/raw/main/webinstall-arm7x

--2024-05-05 10:24:42--  https://github.com/d3vilh/raspberry-gtw-webconfig/raw/main/webinstall-arm7x
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
webinstall-arm7x                 100%[========================================================>]   5.14M   
2024-05-05 10:25:19 (163 KB/s) - 'webinstall-arm7x' saved [5392596/5392596]
```
Add execution permissions to the downloaded file and run it:

```bash
nachalnik@tut:~/raspberry-gateway $ chmod +x webinstall-arm7x
nachalnik@tut:~/raspberry-gateway $ ./webinstall-arm7x
2024/05/05 10:26:04 Welcome! The web interface will guide you on installation process.
Installation logs: webinstall.log
2024/05/05 10:26:04 Starting web server on http://193.169.66.77:8088
^C
nachalnik@tut:~/raspberry-gateway $
```

**Comment by Davide3i** [comment]
Hey @d3vilh, thanks for the quick reply.
I'm installing it on a Raspberry 5 (ARM76) and the ouput of `uname -a` looks like this:
`Linux xxxxxx 6.6.28+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/linux`.
I'm going to try using the proper binary and then I'll get back to you. :)

**Comment by d3vilh** [comment]
Then you should be fine with the standard one, as you have **aarch64**, same as my RPI4 boards:

```bash
user@lol:~/raspberry-gateway $ ./webinstall
2024/05/05 18:07:11 Welcome! The web interface will guide you on installation process.
Installation logs: webinstall.log
2024/05/05 18:07:11 Starting web server on http://192.168.88.2:8088
^C
user@lol:~/raspberry-gateway $ uname -a
Linux lol 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
user@lol:~/raspberry-gateway $
```

I don't have RPI5 yet, but interesting which OS image do you use? 
Your uname output looks like core Debian, not the Raspbian.


You could try to build own `webinstall` binary which will works fine 100% (you need to have Go installed):
Just `git clone https://github.com/d3vilh/raspberry-gtw-webconfig`
then `go build -o webinstall main.go`.

Hmm, now I'm really curious to have RPI5 board (still waiting for CM5 boards, as all my infra laying around CM).

**Comment by Davide3i** [comment]
Good morning @d3vilh, sorry for the delay!
I'm using [Raspberry Pi OS with desktop and recommended software](https://downloads.raspberrypi.com/raspios_full_arm64/release_notes.txt) (64-bit).
I've just read your edits: you can find the `strace` output in my first message, but if you need me to test to run `./webinstall` after installing Go, I may be able to do that this evening.

**Comment by Davide3i** [comment]
Here is the `strace` output.
[webinstall.log](https://github.com/d3vilh/raspberry-gateway/files/15225465/webinstall.log)

**Comment by d3vilh** [comment]
Glad it works. It does means, I have to wait when my Pi5 board will arrive :)
