### ISSUE TITLE
Cannot install Portainer, permission errors

### ISSUE THREAD

**Issue by kroecks** [d3vilh/raspberry-gateway#42]
`
pi@terropi:~/raspberry-gateway $ ./webinstall
2024/07/26 00:47:58 Welcome! The web interface will guide you on installation process.
Installation logs: webinstall.log
2024/07/26 00:47:58 Starting web server on http://192.168.86.33:8088
2024/07/26 00:48:07 http: superfluous response.WriteHeader call from main.editConfig (main.go:397)
[DEPRECATION WARNING]: community.docker.docker_compose has been deprecated.
This module uses docker-compose v1, which is End of Life since July 2022.
Please migrate to community.docker.docker_compose_v2. This feature will be
removed from community.docker in version 4.0.0. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [raspberry_gateway] *******************************************************

TASK [Gathering Facts] *********************************************************
ok: [raspberry_gateway]

TASK [Load configuration (with defaults from example file)] ********************
ok: [raspberry_gateway] => (item=example.config.yml)
ok: [raspberry_gateway] => (item=config.yml)
ok: [raspberry_gateway] => (item=advanced.config.yml)

TASK [Ensure apt cache is up to date] ******************************************
changed: [raspberry_gateway]

TASK [Ensure pacman cache is up to date] ***************************************
skipping: [raspberry_gateway]

TASK [Check if Docker is already present.] *************************************
ok: [raspberry_gateway]

TASK [Download Docker install convenience script.] *****************************
changed: [raspberry_gateway]

TASK [Run Docker install convenience script.] **********************************
changed: [raspberry_gateway]

TASK [Ensure Docker is started.] ***********************************************
ok: [raspberry_gateway]

TASK [Ensure dependencies are installed (Debian).] *****************************
changed: [raspberry_gateway]

TASK [Ensure dependencies are installed (Archlinux).] **************************
skipping: [raspberry_gateway]

TASK [Install Docker Compose with apt.] ****************************************
changed: [raspberry_gateway]

TASK [Ensure pi user is added to the docker group.] ****************************
[WARNING]: Reset is not implemented for this connection
changed: [raspberry_gateway]

TASK [Reset connection so docker group is picked up.] **************************

TASK [Create Portainer folder on Pi.] ******************************************
changed: [raspberry_gateway]

TASK [Pull latest Portainer Docker image] **************************************
fatal: [raspberry_gateway]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))"}

PLAY RECAP *********************************************************************
raspberry_gateway          : ok=11   changed=7    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0

2024/07/26 00:51:25 exit status 2
`

This has been the result from various options of the ansible user. From pi, to custom users.

**Comment by bepp-boop** [comment]
Thanks for writing this, I was stuck with it for a few hours but just assume it is something one my end cause it is on the document.
